const MONSTERS = [
  {name:"Ajarakan",genus:"Fanged Beast",element:"Fire",rank:"5★",attackType:"Technical",
   patterns:{Normal:"T",Overheated:"P"},
   weakElem:{fire:1,water:2,thunder:1,ice:2,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:0,stun:2,bleed:1},
   egg:"Tarkuan - Bountiful Dunes, Rococo Rocks",link:"587100"},
  {name:"Aknosom",genus:"Bird Wyvern",element:"Fire",rank:"3★",attackType:"Technical",
   patterns:{Normal:"T",Enraged:"P"},
   weakElem:{fire:0,water:3,thunder:1,ice:2,dragon:0},ailments:{poison:1,para:1,sleep:2,blast:1,stun:1,bleed:1},
   egg:"Canalta Timberland - Mt. Canalta, Howlinyowl Forest",link:"586452"},
  {name:"Almudron",genus:"Leviathan",element:"Water",rank:"5★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"T","Large Mudbulb":"S"},
   weakElem:{fire:2,water:0,thunder:2,ice:1,dragon:1},ailments:{poison:1,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Tarkuan - Bountiful Dunes, Broadleaf Basin",link:"586551"},
  {name:"Anjanath",genus:"Brute Wyvern",element:"Fire",rank:"4★",attackType:"Power",
   patterns:{Normal:"P","Condense Heat":"T"},
   weakElem:{fire:0,water:3,thunder:1,ice:2,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Azuria - Broadleaf Basin",link:"586309"},
  {name:"Arkveld",genus:"Flying Wyvern",element:"Dragon",rank:"6★",attackType:"Technical",
   patterns:{Normal:"T","Dragon Mantle":"P"},
   weakElem:{fire:2,water:1,thunder:2,ice:1,dragon:0},ailments:{poison:0,para:1,sleep:0,blast:1,stun:1,bleed:1},
   egg:"Serathis - Defeat Arkveld",link:"587113"},
  {name:"Arzuros",genus:"Fanged Beast",element:"Non-Elem",rank:"2★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"T"},
   weakElem:{fire:2,water:1,thunder:1,ice:2,dragon:0},ailments:{poison:2,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Canalta Timberland - Cataracts",link:"586456"},
  {name:"Astalos",genus:"Flying Wyvern",element:"Thunder",rank:"5★",attackType:"Speed",
   patterns:{Normal:"S",Bolt:"P"},
   weakElem:{fire:2,water:1,thunder:0,ice:2,dragon:1},ailments:{poison:1,para:0,sleep:1,blast:1,stun:1,bleed:2},
   egg:"Azuria - Mirror Lake (Defeat Invasive Seregios)",link:"586449"},
  {name:"Aurora Somnacanth",genus:"Leviathan",element:"Ice",rank:"5★",attackType:"Technical",
   patterns:{Normal:"T",Enraged:"S"},
   weakElem:{fire:2,water:0,thunder:2,ice:0,dragon:1},ailments:{poison:1,para:1,sleep:0,blast:1,stun:2,bleed:1},
   egg:"Canalta Timberland",link:"586552"},
  {name:"Azure Rathalos",genus:"Flying Wyvern",element:"Fire",rank:"6★",attackType:"Power",
   patterns:{Normal:"P"},
   weakElem:{fire:0,water:2,thunder:1,ice:2,dragon:3},ailments:{poison:1,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Habitat Restoration - Rathalos Rank A",link:"586793"},
  {name:"Barioth",genus:"Flying Wyvern",element:"Ice",rank:"4★",attackType:"Technical",
   patterns:{Normal:"T",Enraged:"S"},
   weakElem:{fire:3,water:0,thunder:2,ice:0,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:2,stun:1,bleed:1},
   egg:"Repel Invasive Khezu",link:"586593"},
  {name:"Barroth",genus:"Brute Wyvern",element:"Water",rank:"3★",attackType:"Speed",
   patterns:{Normal:"S","Mud Mantle":"T"},
   weakElem:{fire:2,water:0,thunder:1,ice:2,dragon:0},ailments:{poison:2,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Tarkuan",link:"587045"},
  {name:"Bishaten",genus:"Fanged Beast",element:"Non-Elem",rank:"3★",attackType:"Technical",
   patterns:{Normal:"T",Balancing:"S"},
   weakElem:{fire:1,water:1,thunder:2,ice:2,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Canalta Timberland - Blessing Hill",link:"586450"},
  {name:"Black Diablos",genus:"Flying Wyvern",element:"Non-Elem",rank:"6★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"S",Burrowed:"S"},
   weakElem:{fire:1,water:2,thunder:1,ice:3,dragon:1},ailments:{poison:1,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Tarkuan - Bountiful Dunes",link:"587109"},
  {name:"Black Gravios",genus:"Flying Wyvern",element:"Fire",rank:"6★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"T"},
   weakElem:{fire:0,water:3,thunder:1,ice:1,dragon:2},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:0},
   egg:"Tarkuan - Broadleaf Basin",link:"586539"},
  {name:"Blangonga",genus:"Fanged Beast",element:"Ice",rank:"3★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"S"},
   weakElem:{fire:3,water:0,thunder:2,ice:0,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:2,stun:1,bleed:1},
   egg:"Serathis - Glacial Caps",link:null},
  {name:"Blood Orange Bishaten",genus:"Fanged Beast",element:"Fire",rank:"4★",attackType:"Speed",
   patterns:{Normal:"S",Enraged:"P"},
   weakElem:{fire:0,water:2,thunder:2,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:0,stun:1,bleed:1},
   egg:"Tarkuan - Broadleaf Basin, Blightstone Woods",link:"586538"},
  {name:"Bloodbath Diablos",genus:"Flying Wyvern",element:"Non-Elem",rank:"7★",attackType:"Speed",
   patterns:{Normal:"S"},
   weakElem:{fire:1,water:2,thunder:1,ice:3,dragon:1},ailments:{poison:1,para:2,sleep:1,blast:0,stun:1,bleed:1},
   egg:"Habitat Restoration - Diablos Rank S",link:"586795"},
  {name:"Blue Yian Kut-Ku",genus:"Bird Wyvern",element:"Water",rank:"3★",attackType:"Technical",
   patterns:{Normal:"T",Enraged:"S"},
   weakElem:{fire:2,water:0,thunder:2,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:2,blast:1,stun:1,bleed:1},
   egg:"Azuria - Blessing Hill, Howlinyowl Forest",link:"586445"},
  {name:"Boltreaver Astalos",genus:"Flying Wyvern",element:"Thunder",rank:"7★",attackType:"Technical",
   patterns:{Normal:"T"},
   weakElem:{fire:2,water:1,thunder:0,ice:2,dragon:1},ailments:{poison:1,para:0,sleep:1,blast:1,stun:1,bleed:2},
   egg:"Habitat Restoration - Astalos Mutation",link:"586448"},
  {name:"Brachydios",genus:"Brute Wyvern",element:"Non-Elem",rank:"6★",attackType:"Power",
   patterns:{Normal:"P","Slime Active":"S","Slime Depleted":"P"},
   weakElem:{fire:1,water:2,thunder:1,ice:2,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:0,stun:2,bleed:1},
   egg:"Serathis - Blightstone Woods",link:"586541"},
  {name:"Brute Tigrex",genus:"Flying Wyvern",element:"Non-Elem",rank:"6★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"S"},
   weakElem:{fire:1,water:3,thunder:1,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:0,bleed:1},
   egg:"Habitat Restoration - Tigrex Rank A",link:"586608"},
  {name:"Canyne",genus:"Fanged Beast",element:"Non-Elem",rank:"5★",attackType:"Speed",
   patterns:{Normal:"S"},
   weakElem:{fire:1,water:1,thunder:1,ice:1,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Canalta Timberland - Main Story",link:"586451"},
  {name:"Chatacabra",genus:"Amphibian",element:"Non-Elem",rank:"1★",attackType:"Power",
   patterns:{Normal:"P","Rock Mantle":"T"},
   weakElem:{fire:2,water:1,thunder:1,ice:2,dragon:0},ailments:{poison:1,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Azuria - Blessing Hill, Howlinyowl Forest",link:"586322"},
  {name:"Deadeye Yian Garuga",genus:"Bird Wyvern",element:"Fire",rank:"7★",attackType:"Speed",
   patterns:{Normal:"S"},
   weakElem:{fire:0,water:2,thunder:2,ice:2,dragon:1},ailments:{poison:0,para:1,sleep:1,blast:1,stun:1,bleed:2},
   egg:"Habitat Restoration - Rank S w/ 3 5★+ Monsters",link:"586618"},
  {name:"Deviljho",genus:"Brute Wyvern",element:"Dragon",rank:"7★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"S",Starving:"P"},
   weakElem:{fire:2,water:1,thunder:2,ice:1,dragon:3},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Serathis - Old Capital Road",link:"586790"},
  {name:"Diablos",genus:"Flying Wyvern",element:"Non-Elem",rank:"5★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"S",Burrowed:"S"},
   weakElem:{fire:1,water:2,thunder:1,ice:3,dragon:1},ailments:{poison:1,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Tarkuan - Bountiful Dunes",link:"587110"},
  {name:"Dreadking Rathalos",genus:"Flying Wyvern",element:"Fire",rank:"7★",attackType:"Power",
   patterns:{Normal:"P"},
   weakElem:{fire:0,water:2,thunder:1,ice:1,dragon:3},ailments:{poison:1,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Habitat Restoration - Rathalos Rank S w/ 4 Flying Wyverns",link:"586794"},
  {name:"Dreadqueen Rathian",genus:"Flying Wyvern",element:"Fire",rank:"7★",attackType:"Speed",
   patterns:{Normal:"S"},
   weakElem:{fire:0,water:2,thunder:1,ice:1,dragon:3},ailments:{poison:0,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Azuria - Rathian Rank S w/ 3 Poison Monsters",link:"586311"},
  {name:"Ebony Odogaron",genus:"Fanged Wyvern",element:"Dragon",rank:"6★",attackType:"Speed",
   patterns:{Normal:"S",Starving:"S",Frenzied:"P"},
   weakElem:{fire:1,water:2,thunder:1,ice:2,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:0},
   egg:"Tarkuan",link:"587103"},
  {name:"Espinas",genus:"Flying Wyvern",element:"Fire",rank:"6★",attackType:"Power",
   patterns:{Normal:"P",Sleep:"S",Enraged:"P"},
   weakElem:{fire:0,water:1,thunder:2,ice:2,dragon:2},ailments:{poison:0,para:0,sleep:1,blast:1,stun:2,bleed:1},
   egg:"Tarkuan/Azuria - Defeat Espinas",link:"586536"},
  {name:"Fulgur Anjanath",genus:"Brute Wyvern",element:"Thunder",rank:"6★",attackType:"Power",
   patterns:{Normal:"P","Electric Charge":"S","High-Voltage Charge":"S"},
   weakElem:{fire:1,water:2,thunder:0,ice:3,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Serathis",link:"587105"},
  {name:"Garangolm",genus:"Fanged Beast",element:"Non-Elem",rank:"4★",attackType:"Power",
   patterns:{Normal:"P","Lava Mantle":"S","Moss Mantle":"T"},
   weakElem:{fire:2,water:1,thunder:2,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:2,bleed:1},
   egg:"Canalta Timberland / Tarkuan",link:"586547"},
  {name:"Glavenus",genus:"Brute Wyvern",element:"Fire",rank:"5★",attackType:"Speed",
   patterns:{Normal:"S","Overheated Throat":"T","Overheated Tail":"P"},
   weakElem:{fire:0,water:3,thunder:1,ice:2,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Serathis",link:"587099"},
  {name:"Goss Harag",genus:"Fanged Beast",element:"Ice",rank:"5★",attackType:"Power",
   patterns:{Normal:"P","Enraged (Frost Knuckles)":"T","Enraged (Frost Blade)":"S"},
   weakElem:{fire:3,water:0,thunder:1,ice:0,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:2,stun:1,bleed:1},
   egg:"Serathis - Frozen Grotto, Glacial Caps",link:"587107"},
  {name:"Gravios",genus:"Flying Wyvern",element:"Fire",rank:"5★",attackType:"Power",
   patterns:{Normal:"P",Overheated:"T"},
   weakElem:{fire:0,water:3,thunder:1,ice:1,dragon:2},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:0},
   egg:"Serathis",link:"587104"},
  {name:"Great Izuchi",genus:"Bird Wyvern",element:"Non-Elem",rank:"1★",attackType:"Speed",
   patterns:{Normal:"S",Enraged:"P"},
   weakElem:{fire:1,water:1,thunder:2,ice:2,dragon:0},ailments:{poison:2,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Canalta Timberland",link:"586561"},
  {name:"Great Poogie",genus:"Fanged Beast",element:"Non-Elem",rank:"1★",attackType:"Technical",
   patterns:{Normal:"T"},
   weakElem:{fire:1,water:1,thunder:1,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Azuria - Find all Poogies",link:"587097"},
  {name:"Green Nargacuga",genus:"Flying Wyvern",element:"Non-Elem",rank:"5★",attackType:"Speed",
   patterns:{Normal:"S",Enraged:"P"},
   weakElem:{fire:2,water:1,thunder:2,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:2,bleed:1},
   egg:"Habitat Restoration - Nargacuga Rank A",link:"586548"},
  {name:"Green Plesioth",genus:"Piscine Wyvern",element:"Water",rank:"5★",attackType:"Speed",
   patterns:{Normal:"S",Enraged:"T"},
   weakElem:{fire:2,water:0,thunder:3,ice:1,dragon:0},ailments:{poison:1,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Azuria",link:"586315"},
  {name:"Grimclaw Tigrex",genus:"Flying Wyvern",element:"Non-Elem",rank:"7★",attackType:"Power",
   patterns:{Normal:"P"},
   weakElem:{fire:1,water:2,thunder:1,ice:2,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Habitat Restoration - Rank S w/ 4 Power Monsters",link:"586800"},
  {name:"Gypceros",genus:"Bird Wyvern",element:"Non-Elem",rank:"2★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"T"},
   weakElem:{fire:2,water:1,thunder:1,ice:1,dragon:0},ailments:{poison:0,para:1,sleep:1,blast:1,stun:2,bleed:1},
   egg:"Azuria",link:"586320"},
  {name:"Hellblade Glavenus",genus:"Brute Wyvern",element:"Fire",rank:"7★",attackType:"Speed",
   patterns:{Normal:"S"},
   weakElem:{fire:0,water:3,thunder:1,ice:2,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:0,stun:1,bleed:1},
   egg:"Habitat Restoration - Rank S w/ 4 Sharp Appendage Monsters",link:"586792"},
  {name:"Ivory Lagiacrus",genus:"Leviathan",element:"Thunder",rank:"6★",attackType:"Speed",
   patterns:{Normal:"S","Electric Charge":"P","Fulgurite Mantle":"T"},
   weakElem:{fire:2,water:1,thunder:0,ice:2,dragon:1},ailments:{poison:1,para:0,sleep:1,blast:1,stun:1,bleed:2},
   egg:"Azuria - Lagiacrus Rank A Habitat Restoration",link:"586447"},
  {name:"Jade Barroth",genus:"Brute Wyvern",element:"Ice",rank:"4★",attackType:"Power",
   patterns:{Normal:"P","Snow Mantle":"T"},
   weakElem:{fire:3,water:0,thunder:1,ice:0,dragon:1},ailments:{poison:2,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Serathis",link:"587046"},
  {name:"Khezu",genus:"Flying Wyvern",element:"Thunder",rank:"3★",attackType:"Technical",
   patterns:{Normal:"T","Electric Charge":"P"},
   weakElem:{fire:3,water:1,thunder:0,ice:1,dragon:1},ailments:{poison:1,para:0,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Canalta Timberland",link:"586546"},
  {name:"Kula-Ya-Ku",genus:"Bird Wyvern",element:"Non-Elem",rank:"2★",attackType:"Technical",
   patterns:{Normal:"T",Enraged:"P"},
   weakElem:{fire:1,water:2,thunder:1,ice:2,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:1,stun:2,bleed:1},
   egg:"Canalta Timberland",link:"586712"},
  {name:"Lagiacrus",genus:"Leviathan",element:"Thunder",rank:"5★",attackType:"Power",
   patterns:{Normal:"P","Electric Charge":"S","Fully Charged":"T"},
   weakElem:{fire:2,water:1,thunder:0,ice:2,dragon:1},ailments:{poison:1,para:0,sleep:1,blast:1,stun:1,bleed:2},
   egg:"Azuria - Defeat Invasive Plesioth",link:"586310"},
  {name:"Legiana",genus:"Flying Wyvern",element:"Ice",rank:"4★",attackType:"Speed",
   patterns:{Normal:"S",Enraged:"P",Airborne:"T"},
   weakElem:{fire:3,water:0,thunder:2,ice:0,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:2,stun:1,bleed:1},
   egg:"Serathis",link:"587102"},
  {name:"Lunagaron",genus:"Fanged Wyvern",element:"Ice",rank:"5★",attackType:"Speed",
   patterns:{Normal:"S","Ice Mantle":"P"},
   weakElem:{fire:3,water:0,thunder:2,ice:0,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:2,stun:1,bleed:1},
   egg:"Serathis - Frozen Grotto, Glacial Caps",link:"587111"},
  {name:"Magnamalo",genus:"Fanged Wyvern",element:"Non-Elem",rank:"6★",attackType:"Speed",
   patterns:{Normal:"S","Hellfireblight Mantle":"P","Hellfireblight Critical":"T"},
   weakElem:{fire:1,water:3,thunder:1,ice:1,dragon:2},ailments:{poison:1,para:1,sleep:1,blast:0,stun:2,bleed:1},
   egg:"Serathis - Old Capital Road",link:"586563"},
  {name:"Malzeno",genus:"Elder Dragon",element:"Dragon",rank:"7★",attackType:"Speed",
   patterns:{Normal:"S","Blood Rite Active":"T",Exposed:"S"},
   weakElem:{fire:2,water:1,thunder:1,ice:2,dragon:0},ailments:{poison:1,para:1,sleep:0,blast:1,stun:1,bleed:0},
   egg:"Serathis - Defeat Malzeno",link:"587471"},
  {name:"Mizutsune",genus:"Leviathan",element:"Water",rank:"5★",attackType:"Technical",
   patterns:{Normal:"T","Bubble Mantle":"S","Bubble Mantle (Slippery)":"S"},
   weakElem:{fire:2,water:0,thunder:3,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:2,stun:1,bleed:1},
   egg:"Canalta Timberland - Defeat Invasive Shogun Ceanataur",link:"586535"},
  {name:"Namielle",genus:"Elder Dragon",element:"Water",rank:"7★",attackType:"Technical",
   patterns:{Normal:"T","Abyssal Charge":"S","Water Depleted":"P"},
   weakElem:{fire:3,water:0,thunder:1,ice:1,dragon:2},ailments:{poison:1,para:1,sleep:0,blast:1,stun:1,bleed:0},
   egg:"Azuria - Defeat Namielle",link:"587517"},
  {name:"Nargacuga",genus:"Flying Wyvern",element:"Non-Elem",rank:"4★",attackType:"Speed",
   patterns:{Normal:"S",Camouflaged:"T"},
   weakElem:{fire:2,water:1,thunder:2,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:2,bleed:1},
   egg:"Canalta Timberland - Defeat Invasive Nerscylla",link:"586549"},
  {name:"Nerscylla",genus:"Temnoceran",element:"Non-Elem",rank:"3★",attackType:"Technical",
   patterns:{Normal:"T","No Web":"S"},
   weakElem:{fire:2,water:1,thunder:2,ice:1,dragon:0},ailments:{poison:0,para:1,sleep:0,blast:1,stun:1,bleed:1},
   egg:"Azuria",link:"586323"},
  {name:"Odogaron",genus:"Fanged Wyvern",element:"Non-Elem",rank:"5★",attackType:"Speed",
   patterns:{Normal:"S",Enraged:"S",Frenzied:"P"},
   weakElem:{fire:1,water:1,thunder:2,ice:2,dragon:1},ailments:{poison:1,para:2,sleep:1,blast:1,stun:1,bleed:0},
   egg:"Tarkuan - Death's Maw",link:"587112"},
  {name:"Paolumu",genus:"Flying Wyvern",element:"Non-Elem",rank:"3★",attackType:"Technical",
   patterns:{Normal:"T",Enraged:"S"},
   weakElem:{fire:2,water:1,thunder:1,ice:1,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:2,stun:1,bleed:1},
   egg:"Azuria",link:"586324"},
  {name:"Pink Rathian",genus:"Flying Wyvern",element:"Fire",rank:"5★",attackType:"Speed",
   patterns:{Normal:"S",Enraged:"P"},
   weakElem:{fire:0,water:2,thunder:2,ice:1,dragon:2},ailments:{poison:0,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Azuria - Rathian Rank B Habitat Restoration",link:"586312"},
  {name:"Plesioth",genus:"Piscine Wyvern",element:"Water",rank:"4★",attackType:"Speed",
   patterns:{Normal:"S",Enraged:"P"},
   weakElem:{fire:2,water:0,thunder:3,ice:1,dragon:0},ailments:{poison:1,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Azuria",link:"586316"},
  {name:"Pukei-Pukei",genus:"Bird Wyvern",element:"Water",rank:"3★",attackType:"Technical",
   patterns:{Normal:"T","Poison Active (Munch)":"S","Poison Active (Crunch)":"P"},
   weakElem:{fire:2,water:0,thunder:2,ice:1,dragon:0},ailments:{poison:0,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Canalta Timberland",link:"586545"},
  {name:"Purple Gypceros",genus:"Bird Wyvern",element:"Non-Elem",rank:"3★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"T"},
   weakElem:{fire:2,water:1,thunder:1,ice:1,dragon:0},ailments:{poison:0,para:1,sleep:1,blast:1,stun:2,bleed:1},
   egg:"Azuria",link:"586319"},
  {name:"Purple Ludroth",genus:"Leviathan",element:"Non-Elem",rank:"3★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"T"},
   weakElem:{fire:2,water:1,thunder:2,ice:1,dragon:0},ailments:{poison:0,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Canalta Timberland",link:"586453"},
  {name:"Rakna-Kadaki",genus:"Temnoceran",element:"Fire",rank:"5★",attackType:"Technical",
   patterns:{Normal:"T","Web Mantle":"T","No Web":"S"},
   weakElem:{fire:0,water:3,thunder:1,ice:2,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:2,bleed:0},
   egg:"Tarkuan",link:"587106"},
  {name:"Rathalos",genus:"Flying Wyvern",element:"Fire",rank:"5★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"T","Enraged (Airborne)":"S"},
   weakElem:{fire:0,water:2,thunder:1,ice:1,dragon:3},ailments:{poison:1,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Serathis",link:"587108"},
  {name:"Rathian",genus:"Flying Wyvern",element:"Fire",rank:"4★",attackType:"Speed",
   patterns:{Normal:"S",Enraged:"P"},
   weakElem:{fire:0,water:2,thunder:2,ice:1,dragon:2},ailments:{poison:0,para:2,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Azuria",link:"586313"},
  {name:"Red Khezu",genus:"Flying Wyvern",element:"Thunder",rank:"4★",attackType:"Technical",
   patterns:{Normal:"T","Electric Charge":"P"},
   weakElem:{fire:3,water:1,thunder:0,ice:1,dragon:1},ailments:{poison:1,para:0,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Canalta Timberland",link:"586544"},
  {name:"Rey Dau",genus:"Flying Wyvern",element:"Thunder",rank:"6★",attackType:"Speed",
   patterns:{Normal:"S","Electric Charge":"S","Thunder Supercharge":"P"},
   weakElem:{fire:1,water:2,thunder:0,ice:2,dragon:2},ailments:{poison:1,para:0,sleep:1,blast:1,stun:1,bleed:2},
   egg:"Tarkuan - Defeat Rey Dau",link:"587470"},
  {name:"Royal Ludroth",genus:"Leviathan",element:"Water",rank:"2★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"T"},
   weakElem:{fire:3,water:0,thunder:2,ice:1,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Azuria",link:"586317"},
  {name:"Sand Barioth",genus:"Flying Wyvern",element:"Non-Elem",rank:"5★",attackType:"Technical",
   patterns:{Normal:"T",Enraged:"S"},
   weakElem:{fire:0,water:2,thunder:2,ice:2,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:2,stun:1,bleed:1},
   egg:"Habitat Restoration - Barioth Rank S",link:"586605"},
  {name:"Seregios",genus:"Flying Wyvern",element:"Non-Elem",rank:"6★",attackType:"Speed",
   patterns:{Normal:"S","Enraged (Airborne)":"P",Airborne:"T"},
   weakElem:{fire:1,water:1,thunder:2,ice:2,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:0},
   egg:"Canalta Timberland - Mt. Canalta",link:"586550"},
  {name:"Shogun Ceanataur",genus:"Carapaceon",element:"Water",rank:"3★",attackType:"Speed",
   patterns:{Normal:"S","Shell (Skull)":"T","No Shell":"P"},
   weakElem:{fire:2,water:0,thunder:3,ice:1,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:0},
   egg:"Tarkuan",link:"587114"},
  {name:"Shrouded Nerscylla",genus:"Temnoceran",element:"Non-Elem",rank:"4★",attackType:"Technical",
   patterns:{Normal:"T","No Web":"S"},
   weakElem:{fire:2,water:1,thunder:2,ice:1,dragon:0},ailments:{poison:0,para:0,sleep:0,blast:1,stun:1,bleed:1},
   egg:"Tarkuan",link:"587098"},
  {name:"Silverwind Nargacuga",genus:"Flying Wyvern",element:"Non-Elem",rank:"7★",attackType:"Speed",
   patterns:{Normal:"S"},
   weakElem:{fire:2,water:1,thunder:2,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:2,bleed:1},
   egg:"Canalta Timberland - Nargacuga Rank S w/ 3 Wind Monsters",link:"586542"},
  {name:"Somnacanth",genus:"Leviathan",element:"Water",rank:"4★",attackType:"Technical",
   patterns:{Normal:"T",Sleep:"S",Enraged:"S"},
   weakElem:{fire:2,water:0,thunder:2,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:0,blast:1,stun:2,bleed:1},
   egg:"Canalta Timberland",link:"586457"},
  {name:"Soulseer Mizutsune",genus:"Leviathan",element:"Water",rank:"7★",attackType:"Speed",
   patterns:{Normal:"S"},
   weakElem:{fire:2,water:0,thunder:3,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:2,stun:1,bleed:1},
   egg:"Habitat Restoration - Rank S w/ Zinogre",link:"586606"},
  {name:"Stygian Zinogre",genus:"Fanged Wyvern",element:"Dragon",rank:"6★",attackType:"Technical",
   patterns:{Normal:"T","Blightstone Protection":"S","Blightstone Unleashed":"P"},
   weakElem:{fire:1,water:2,thunder:1,ice:2,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Habitat Restoration - Zinogre Rank A",link:"586607"},
  {name:"Tetranadon",genus:"Amphibian",element:"Water",rank:"3★",attackType:"Power",
   patterns:{Normal:"P",Stuffed:"T"},
   weakElem:{fire:2,water:0,thunder:2,ice:1,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:1,stun:2,bleed:1},
   egg:"Canalta Timberland",link:"586455"},
  {name:"Thunder Serpent Narwa",genus:"Elder Dragon",element:"Thunder",rank:"7★",attackType:"Speed",
   patterns:{Normal:"S"},
   weakElem:{fire:2,water:1,thunder:0,ice:2,dragon:2},ailments:{poison:1,para:0,sleep:1,blast:1,stun:0,bleed:1},
   egg:null,link:"587513"},
  {name:"Thunderlord Zinogre",genus:"Fanged Wyvern",element:"Thunder",rank:"7★",attackType:"Power",
   patterns:{Normal:"P"},
   weakElem:{fire:1,water:2,thunder:0,ice:3,dragon:1},ailments:{poison:1,para:0,sleep:1,blast:1,stun:1,bleed:2},
   egg:"Habitat Restoration - Rank S w/ Mizutsune",link:"586796"},
  {name:"Tigrex",genus:"Flying Wyvern",element:"Non-Elem",rank:"5★",attackType:"Power",
   patterns:{Normal:"P",Enraged:"S"},
   weakElem:{fire:1,water:2,thunder:1,ice:2,dragon:1},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Repel Invasive Diablos",link:"586559"},
  {name:"Tobi-Kadachi",genus:"Fanged Wyvern",element:"Thunder",rank:"3★",attackType:"Speed",
   patterns:{Normal:"S","Electric Charge":"T"},
   weakElem:{fire:2,water:2,thunder:0,ice:1,dragon:0},ailments:{poison:1,para:0,sleep:1,blast:1,stun:1,bleed:2},
   egg:"Azuria",link:"586318"},
  {name:"Velkhana",genus:"Elder Dragon",element:"Ice",rank:"7★",attackType:"Technical",
   patterns:{Normal:"T","Ice Mantle":"S",Enraged:"T"},
   weakElem:{fire:3,water:0,thunder:1,ice:0,dragon:2},ailments:{poison:1,para:1,sleep:0,blast:2,stun:1,bleed:0},
   egg:"Serathis - Defeat Velkhana",link:"587515"},
  {name:"Velocidrome",genus:"Bird Wyvern",element:"Non-Elem",rank:"1★",attackType:"Speed",
   patterns:{Normal:"S",Enraged:"P"},
   weakElem:{fire:1,water:1,thunder:2,ice:2,dragon:0},ailments:{poison:2,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:"Azuria",link:"586321"},
  {name:"Wind Serpent Ibushi",genus:"Elder Dragon",element:"Dragon",rank:"7★",attackType:"Power",
   patterns:{Normal:"P"},
   weakElem:{fire:1,water:2,thunder:2,ice:1,dragon:0},ailments:{poison:1,para:1,sleep:0,blast:1,stun:1,bleed:0},
   egg:null,link:"587514"},
  {name:"Yama Tsukami",genus:"Elder Dragon",element:"Dragon",rank:"7★",attackType:"Power",
   patterns:{Normal:"P","Open Mouth":"S"},
   weakElem:{fire:2,water:1,thunder:2,ice:1,dragon:0},ailments:{poison:0,para:1,sleep:0,blast:1,stun:1,bleed:0},
   egg:null,link:"587518"},
  {name:"Yian Garuga",genus:"Bird Wyvern",element:"Fire",rank:"4★",attackType:"Technical",
   patterns:{Normal:"T",Enraged:"P"},
   weakElem:{fire:0,water:2,thunder:2,ice:2,dragon:1},ailments:{poison:0,para:1,sleep:1,blast:1,stun:1,bleed:2},
   egg:"Canalta Timberland",link:"586543"},
  {name:"Yian Kut-Ku",genus:"Bird Wyvern",element:"Fire",rank:"2★",attackType:"Technical",
   patterns:{Normal:"T",Enraged:"S"},
   weakElem:{fire:0,water:2,thunder:2,ice:1,dragon:1},ailments:{poison:1,para:1,sleep:2,blast:1,stun:1,bleed:1},
   egg:"Azuria",link:"586325"},
  {name:"Zinogre",genus:"Fanged Wyvern",element:"Thunder",rank:"5★",attackType:"Speed",
   patterns:{Normal:"S","Electric Charge":"T",Electrify:"P"},
   weakElem:{fire:1,water:2,thunder:0,ice:3,dragon:1},ailments:{poison:1,para:0,sleep:1,blast:1,stun:1,bleed:2},
   egg:"Repel Invasive Odogaron",link:"586564"},
  {name:"Nibelsnarf",genus:"Leviathan",element:"Non-Elem",rank:"4★",attackType:"Technical",
   patterns:{Normal:"T","Open Mouth":"S"},
   weakElem:{fire:1,water:1,thunder:2,ice:2,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:2,stun:1,bleed:1},
   egg:"Tarkuan",link:"586540"},
  {name:"Bnahabra",genus:"Bird Wyvern",element:"Non-Elem",rank:"1★",attackType:"Technical",
   patterns:{Normal:"T"},
   weakElem:{fire:2,water:1,thunder:1,ice:1,dragon:0},ailments:{poison:0,para:1,sleep:1,blast:1,stun:2,bleed:1},
   egg:null,link:"586653"},
  {name:"Gargwa",genus:"Bird Wyvern",element:"Non-Elem",rank:"1★",attackType:"Speed",
   patterns:{Normal:"S"},
   weakElem:{fire:1,water:1,thunder:1,ice:1,dragon:0},ailments:{poison:1,para:1,sleep:1,blast:1,stun:1,bleed:1},
   egg:null,link:"586697"}
];
